### PR TITLE
Add banner to notify about the new Stately Visualizer

### PR DESCRIPTION
**Pull request by farskid**
CleanShot 2022-10-11 at 20 41 09@2x

### CODE REVIEW

**Comment by farskid** [comment]
cc @davidkpiano

**Comment by kevinmaes** [comment]
@farskid There's a ton of changes related to Prettier formatting. No big deal but what if we just create another branch and run Prettier on the entire project as a way to reduce the diff here but also to make the whole project prettier for the next time? Just a thought if we assume it won't be risky at all which it shouldn't be.

**Comment by farskid** [comment]
> @farskid There's a ton of changes related to Prettier formatting. No big deal but what if we just create another branch and run Prettier on the entire project as a way to reduce the diff here but also to make the whole project prettier for the next time? Just a thought if we assume it won't be risky at all which it shouldn't be.

I'm not opposed to this idea but this is a very old codebase and won't be maintained soon 🤷‍♂️

**Comment by davidkpiano** [comment]
@farskid Nit: can we add an orange BG color? (Stately orange)

**Comment by kevinmaes** [comment]
> > @farskid There's a ton of changes related to Prettier formatting. No big deal but what if we just create another branch and run Prettier on the entire project as a way to reduce the diff here but also to make the whole project prettier for the next time? Just a thought if we assume it won't be risky at all which it shouldn't be.
> 
> I'm not opposed to this idea but this is a very old codebase and won't be maintained soon 🤷‍♂️

Understood. If we're not really maintaining it then perhaps there's more risk than reward in that case. Or another approach is to just turn off your Prettier and make the min changes even in this PR. But it's a nit so whatever is easiest to do.

**Comment by farskid** [comment]
> @farskid Nit: can we add an orange BG color? (Stately orange)

CleanShot 2022-10-11 at 21 35 09@2x

**Comment by farskid** [comment]
> > > @farskid There's a ton of changes related to Prettier formatting. No big deal but what if we just create another branch and run Prettier on the entire project as a way to reduce the diff here but also to make the whole project prettier for the next time? Just a thought if we assume it won't be risky at all which it shouldn't be.
> > 
> > 
> > I'm not opposed to this idea but this is a very old codebase and won't be maintained soon 🤷‍♂️
> 
> Understood. If we're not really maintaining it then perhaps there's more risk than reward in that case. Or another approach is to just turn off your Prettier and make the min changes even in this PR. But it's a nit so whatever is easiest to do.

Done.

**Review by davidkpiano — APPROVED** [review]

**Pull request merged**
